version: '2.1'
volumes:
  db:
services:
  mongo:
    image: xagh/mongo_facturas_jhon
    # volumes:
    #   - db:/data/db
    ports:
      - "27017:27017"
    restart: always
  
  # app:
  #   build:
  #     context: .
  #   image: facturas_jhon:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   volumes:
  #     - .:/app
  #   restart: always