version: '2.1'
volumes:
  db:
services:
  mongo:
    image: mvertes/alpine-mongo
    # volumes:
    #   - db:/data/db
    ports:
      - "27017:27017"
    restart: always
    container_name: mongo
  
  # back:
  #   build: ./backend
  #   image: back_facturas_jhon:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo 
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - APP_MONGO_HOST=mongo
  #     - PRODUCTION_ENV=27017
  #   restart: always
  #   container_name: back

  # front:
  #   build: ./frontend
  #   image: front_facturas_jhon:latest
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - back
  #   volumes:
  #     - /front/node_modules
  #     - ./frontend:/front
  #   restart: always
  #   container_name: front
